# Generated by Django 4.1 on 2023-05-27 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='service_image/')),
                ('score', models.CharField(blank=True, choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], max_length=5)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='Create_Services', to='api.category_createservice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Create_Service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='api.category_service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.create_service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy', models.BooleanField(default=False)),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reserve', to='api.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reserves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
