# Generated by Django 4.2.1 on 2023-06-01 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_service_service_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pos_image/')),
                ('dislike', models.ManyToManyField(blank=True, null=True, related_name='post_dislike', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.create_service')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=1)),
                ('desc', models.TextField(max_length=700)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reply', models.BooleanField(default=False)),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_key', to='api.create_service')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentid', to='api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
