# Generated by Django 4.1 on 2023-05-27 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='api.category_service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.create_service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy', models.BooleanField(default=False)),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reserve', to='api.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reserves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pos_image/')),
                ('dislike', models.ManyToManyField(blank=True, null=True, related_name='post_dislike', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='post_like', to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.create_service')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=1)),
                ('desc', models.TextField(max_length=700)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reply', models.BooleanField(default=False)),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_key', to='api.create_service')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentid', to='api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
