# Generated by Django 4.2.1 on 2023-06-04 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_post_key_comment_hairstyle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='image',
            name='like',
        ),
        migrations.AddField(
            model_name='image',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
