# Generated by Django 4.2.2 on 2023-06-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_image_dislike_remove_image_like_like_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='HairStyle',
            new_name='post_kay',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
