# Generated by Django 4.2.2 on 2023-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_hairstyle_comment_post_kay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
